/* Generated by tools/gen_com_stubs.py from the Windows SDK DirectX 7 headers. Do not edit. */
#pragma once
#include "common.h"

struct IDirectDraw7Stubs : IDirectDraw7 {
    HRESULT STDMETHODCALLTYPE Compact() override { unimplemented("IDirectDraw7::Compact"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateClipper(DWORD, LPDIRECTDRAWCLIPPER FAR*, IUnknown FAR *) override { unimplemented("IDirectDraw7::CreateClipper"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreatePalette(DWORD, LPPALETTEENTRY, LPDIRECTDRAWPALETTE FAR*, IUnknown FAR *) override { unimplemented("IDirectDraw7::CreatePalette"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateSurface(LPDDSURFACEDESC2, LPDIRECTDRAWSURFACE7 FAR *, IUnknown FAR *) override { unimplemented("IDirectDraw7::CreateSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DuplicateSurface(LPDIRECTDRAWSURFACE7, LPDIRECTDRAWSURFACE7 FAR *) override { unimplemented("IDirectDraw7::DuplicateSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumDisplayModes(DWORD, LPDDSURFACEDESC2, LPVOID, LPDDENUMMODESCALLBACK2) override { unimplemented("IDirectDraw7::EnumDisplayModes"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumSurfaces(DWORD, LPDDSURFACEDESC2, LPVOID,LPDDENUMSURFACESCALLBACK7) override { unimplemented("IDirectDraw7::EnumSurfaces"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE FlipToGDISurface() override { unimplemented("IDirectDraw7::FlipToGDISurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetCaps(LPDDCAPS, LPDDCAPS) override { unimplemented("IDirectDraw7::GetCaps"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetDisplayMode(LPDDSURFACEDESC2) override { unimplemented("IDirectDraw7::GetDisplayMode"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetFourCCCodes(LPDWORD, LPDWORD) override { unimplemented("IDirectDraw7::GetFourCCCodes"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetGDISurface(LPDIRECTDRAWSURFACE7 FAR *) override { unimplemented("IDirectDraw7::GetGDISurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetMonitorFrequency(LPDWORD) override { unimplemented("IDirectDraw7::GetMonitorFrequency"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetScanLine(LPDWORD) override { unimplemented("IDirectDraw7::GetScanLine"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetVerticalBlankStatus(LPBOOL) override { unimplemented("IDirectDraw7::GetVerticalBlankStatus"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Initialize(GUID FAR *) override { unimplemented("IDirectDraw7::Initialize"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE RestoreDisplayMode() override { unimplemented("IDirectDraw7::RestoreDisplayMode"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetCooperativeLevel(HWND, DWORD) override { unimplemented("IDirectDraw7::SetCooperativeLevel"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetDisplayMode(DWORD, DWORD,DWORD, DWORD, DWORD) override { unimplemented("IDirectDraw7::SetDisplayMode"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE WaitForVerticalBlank(DWORD, HANDLE) override { unimplemented("IDirectDraw7::WaitForVerticalBlank"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetAvailableVidMem(LPDDSCAPS2, LPDWORD, LPDWORD) override { unimplemented("IDirectDraw7::GetAvailableVidMem"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetSurfaceFromDC(HDC, LPDIRECTDRAWSURFACE7 *) override { unimplemented("IDirectDraw7::GetSurfaceFromDC"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE RestoreAllSurfaces() override { unimplemented("IDirectDraw7::RestoreAllSurfaces"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE TestCooperativeLevel() override { unimplemented("IDirectDraw7::TestCooperativeLevel"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetDeviceIdentifier(LPDDDEVICEIDENTIFIER2, DWORD) override { unimplemented("IDirectDraw7::GetDeviceIdentifier"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE StartModeTest(LPSIZE, DWORD, DWORD) override { unimplemented("IDirectDraw7::StartModeTest"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EvaluateMode(DWORD, DWORD *) override { unimplemented("IDirectDraw7::EvaluateMode"); return E_NOTIMPL; }
};

struct IDirectDrawSurface7Stubs : IDirectDrawSurface7 {
    HRESULT STDMETHODCALLTYPE AddAttachedSurface(LPDIRECTDRAWSURFACE7) override { unimplemented("IDirectDrawSurface7::AddAttachedSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE AddOverlayDirtyRect(LPRECT) override { unimplemented("IDirectDrawSurface7::AddOverlayDirtyRect"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Blt(LPRECT,LPDIRECTDRAWSURFACE7, LPRECT,DWORD, LPDDBLTFX) override { unimplemented("IDirectDrawSurface7::Blt"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE BltBatch(LPDDBLTBATCH, DWORD, DWORD) override { unimplemented("IDirectDrawSurface7::BltBatch"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE BltFast(DWORD,DWORD,LPDIRECTDRAWSURFACE7, LPRECT,DWORD) override { unimplemented("IDirectDrawSurface7::BltFast"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DeleteAttachedSurface(DWORD,LPDIRECTDRAWSURFACE7) override { unimplemented("IDirectDrawSurface7::DeleteAttachedSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumAttachedSurfaces(LPVOID,LPDDENUMSURFACESCALLBACK7) override { unimplemented("IDirectDrawSurface7::EnumAttachedSurfaces"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumOverlayZOrders(DWORD,LPVOID,LPDDENUMSURFACESCALLBACK7) override { unimplemented("IDirectDrawSurface7::EnumOverlayZOrders"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Flip(LPDIRECTDRAWSURFACE7, DWORD) override { unimplemented("IDirectDrawSurface7::Flip"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetAttachedSurface(LPDDSCAPS2, LPDIRECTDRAWSURFACE7 FAR *) override { unimplemented("IDirectDrawSurface7::GetAttachedSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetBltStatus(DWORD) override { unimplemented("IDirectDrawSurface7::GetBltStatus"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetCaps(LPDDSCAPS2) override { unimplemented("IDirectDrawSurface7::GetCaps"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetClipper(LPDIRECTDRAWCLIPPER FAR*) override { unimplemented("IDirectDrawSurface7::GetClipper"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetColorKey(DWORD, LPDDCOLORKEY) override { unimplemented("IDirectDrawSurface7::GetColorKey"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetDC(HDC FAR *) override { unimplemented("IDirectDrawSurface7::GetDC"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetFlipStatus(DWORD) override { unimplemented("IDirectDrawSurface7::GetFlipStatus"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetOverlayPosition(LPLONG, LPLONG) override { unimplemented("IDirectDrawSurface7::GetOverlayPosition"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetPalette(LPDIRECTDRAWPALETTE FAR*) override { unimplemented("IDirectDrawSurface7::GetPalette"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetPixelFormat(LPDDPIXELFORMAT) override { unimplemented("IDirectDrawSurface7::GetPixelFormat"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetSurfaceDesc(LPDDSURFACEDESC2) override { unimplemented("IDirectDrawSurface7::GetSurfaceDesc"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Initialize(LPDIRECTDRAW, LPDDSURFACEDESC2) override { unimplemented("IDirectDrawSurface7::Initialize"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE IsLost() override { unimplemented("IDirectDrawSurface7::IsLost"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Lock(LPRECT,LPDDSURFACEDESC2,DWORD,HANDLE) override { unimplemented("IDirectDrawSurface7::Lock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE ReleaseDC(HDC) override { unimplemented("IDirectDrawSurface7::ReleaseDC"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Restore() override { unimplemented("IDirectDrawSurface7::Restore"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetClipper(LPDIRECTDRAWCLIPPER) override { unimplemented("IDirectDrawSurface7::SetClipper"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetColorKey(DWORD, LPDDCOLORKEY) override { unimplemented("IDirectDrawSurface7::SetColorKey"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetOverlayPosition(LONG, LONG) override { unimplemented("IDirectDrawSurface7::SetOverlayPosition"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetPalette(LPDIRECTDRAWPALETTE) override { unimplemented("IDirectDrawSurface7::SetPalette"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Unlock(LPRECT) override { unimplemented("IDirectDrawSurface7::Unlock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE UpdateOverlay(LPRECT, LPDIRECTDRAWSURFACE7,LPRECT,DWORD, LPDDOVERLAYFX) override { unimplemented("IDirectDrawSurface7::UpdateOverlay"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE UpdateOverlayDisplay(DWORD) override { unimplemented("IDirectDrawSurface7::UpdateOverlayDisplay"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE UpdateOverlayZOrder(DWORD, LPDIRECTDRAWSURFACE7) override { unimplemented("IDirectDrawSurface7::UpdateOverlayZOrder"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetDDInterface(LPVOID FAR *) override { unimplemented("IDirectDrawSurface7::GetDDInterface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE PageLock(DWORD) override { unimplemented("IDirectDrawSurface7::PageLock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE PageUnlock(DWORD) override { unimplemented("IDirectDrawSurface7::PageUnlock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetSurfaceDesc(LPDDSURFACEDESC2, DWORD) override { unimplemented("IDirectDrawSurface7::SetSurfaceDesc"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetPrivateData(REFGUID, LPVOID, DWORD, DWORD) override { unimplemented("IDirectDrawSurface7::SetPrivateData"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetPrivateData(REFGUID, LPVOID, LPDWORD) override { unimplemented("IDirectDrawSurface7::GetPrivateData"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE FreePrivateData(REFGUID) override { unimplemented("IDirectDrawSurface7::FreePrivateData"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetUniquenessValue(LPDWORD) override { unimplemented("IDirectDrawSurface7::GetUniquenessValue"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE ChangeUniquenessValue() override { unimplemented("IDirectDrawSurface7::ChangeUniquenessValue"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetPriority(DWORD) override { unimplemented("IDirectDrawSurface7::SetPriority"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetPriority(LPDWORD) override { unimplemented("IDirectDrawSurface7::GetPriority"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetLOD(DWORD) override { unimplemented("IDirectDrawSurface7::SetLOD"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetLOD(LPDWORD) override { unimplemented("IDirectDrawSurface7::GetLOD"); return E_NOTIMPL; }
};

struct IDirectDrawPaletteStubs : IDirectDrawPalette {
    HRESULT STDMETHODCALLTYPE GetCaps(LPDWORD) override { unimplemented("IDirectDrawPalette::GetCaps"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetEntries(DWORD,DWORD,DWORD,LPPALETTEENTRY) override { unimplemented("IDirectDrawPalette::GetEntries"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Initialize(LPDIRECTDRAW, DWORD, LPPALETTEENTRY) override { unimplemented("IDirectDrawPalette::Initialize"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetEntries(DWORD,DWORD,DWORD,LPPALETTEENTRY) override { unimplemented("IDirectDrawPalette::SetEntries"); return E_NOTIMPL; }
};

struct IDirectDrawClipperStubs : IDirectDrawClipper {
    HRESULT STDMETHODCALLTYPE GetClipList(LPRECT, LPRGNDATA, LPDWORD) override { unimplemented("IDirectDrawClipper::GetClipList"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetHWnd(HWND FAR *) override { unimplemented("IDirectDrawClipper::GetHWnd"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Initialize(LPDIRECTDRAW, DWORD) override { unimplemented("IDirectDrawClipper::Initialize"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE IsClipListChanged(BOOL FAR *) override { unimplemented("IDirectDrawClipper::IsClipListChanged"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetClipList(LPRGNDATA,DWORD) override { unimplemented("IDirectDrawClipper::SetClipList"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetHWnd(DWORD, HWND) override { unimplemented("IDirectDrawClipper::SetHWnd"); return E_NOTIMPL; }
};

struct IDirect3D7Stubs : IDirect3D7 {
    HRESULT STDMETHODCALLTYPE EnumDevices(LPD3DENUMDEVICESCALLBACK7,LPVOID) override { unimplemented("IDirect3D7::EnumDevices"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateDevice(REFCLSID,LPDIRECTDRAWSURFACE7,LPDIRECT3DDEVICE7*) override { unimplemented("IDirect3D7::CreateDevice"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateVertexBuffer(LPD3DVERTEXBUFFERDESC,LPDIRECT3DVERTEXBUFFER7*,DWORD) override { unimplemented("IDirect3D7::CreateVertexBuffer"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumZBufferFormats(REFCLSID,LPD3DENUMPIXELFORMATSCALLBACK,LPVOID) override { unimplemented("IDirect3D7::EnumZBufferFormats"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EvictManagedTextures() override { unimplemented("IDirect3D7::EvictManagedTextures"); return E_NOTIMPL; }
};

struct IDirect3DDevice7Stubs : IDirect3DDevice7 {
    HRESULT STDMETHODCALLTYPE GetCaps(LPD3DDEVICEDESC7) override { unimplemented("IDirect3DDevice7::GetCaps"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumTextureFormats(LPD3DENUMPIXELFORMATSCALLBACK,LPVOID) override { unimplemented("IDirect3DDevice7::EnumTextureFormats"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE BeginScene() override { unimplemented("IDirect3DDevice7::BeginScene"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EndScene() override { unimplemented("IDirect3DDevice7::EndScene"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetDirect3D(LPDIRECT3D7*) override { unimplemented("IDirect3DDevice7::GetDirect3D"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetRenderTarget(LPDIRECTDRAWSURFACE7,DWORD) override { unimplemented("IDirect3DDevice7::SetRenderTarget"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetRenderTarget(LPDIRECTDRAWSURFACE7 *) override { unimplemented("IDirect3DDevice7::GetRenderTarget"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Clear(DWORD,LPD3DRECT,DWORD,D3DCOLOR,D3DVALUE,DWORD) override { unimplemented("IDirect3DDevice7::Clear"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetTransform(D3DTRANSFORMSTATETYPE,LPD3DMATRIX) override { unimplemented("IDirect3DDevice7::SetTransform"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetTransform(D3DTRANSFORMSTATETYPE,LPD3DMATRIX) override { unimplemented("IDirect3DDevice7::GetTransform"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetViewport(LPD3DVIEWPORT7) override { unimplemented("IDirect3DDevice7::SetViewport"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE MultiplyTransform(D3DTRANSFORMSTATETYPE,LPD3DMATRIX) override { unimplemented("IDirect3DDevice7::MultiplyTransform"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetViewport(LPD3DVIEWPORT7) override { unimplemented("IDirect3DDevice7::GetViewport"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetMaterial(LPD3DMATERIAL7) override { unimplemented("IDirect3DDevice7::SetMaterial"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetMaterial(LPD3DMATERIAL7) override { unimplemented("IDirect3DDevice7::GetMaterial"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetLight(DWORD,LPD3DLIGHT7) override { unimplemented("IDirect3DDevice7::SetLight"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetLight(DWORD,LPD3DLIGHT7) override { unimplemented("IDirect3DDevice7::GetLight"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetRenderState(D3DRENDERSTATETYPE,DWORD) override { unimplemented("IDirect3DDevice7::SetRenderState"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetRenderState(D3DRENDERSTATETYPE,LPDWORD) override { unimplemented("IDirect3DDevice7::GetRenderState"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE BeginStateBlock() override { unimplemented("IDirect3DDevice7::BeginStateBlock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EndStateBlock(LPDWORD) override { unimplemented("IDirect3DDevice7::EndStateBlock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE PreLoad(LPDIRECTDRAWSURFACE7) override { unimplemented("IDirect3DDevice7::PreLoad"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DrawPrimitive(D3DPRIMITIVETYPE,DWORD,LPVOID,DWORD,DWORD) override { unimplemented("IDirect3DDevice7::DrawPrimitive"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DrawIndexedPrimitive(D3DPRIMITIVETYPE,DWORD,LPVOID,DWORD,LPWORD,DWORD,DWORD) override { unimplemented("IDirect3DDevice7::DrawIndexedPrimitive"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetClipStatus(LPD3DCLIPSTATUS) override { unimplemented("IDirect3DDevice7::SetClipStatus"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetClipStatus(LPD3DCLIPSTATUS) override { unimplemented("IDirect3DDevice7::GetClipStatus"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DrawPrimitiveStrided(D3DPRIMITIVETYPE,DWORD,LPD3DDRAWPRIMITIVESTRIDEDDATA,DWORD,DWORD) override { unimplemented("IDirect3DDevice7::DrawPrimitiveStrided"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DrawIndexedPrimitiveStrided(D3DPRIMITIVETYPE,DWORD,LPD3DDRAWPRIMITIVESTRIDEDDATA,DWORD,LPWORD,DWORD,DWORD) override { unimplemented("IDirect3DDevice7::DrawIndexedPrimitiveStrided"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DrawPrimitiveVB(D3DPRIMITIVETYPE,LPDIRECT3DVERTEXBUFFER7,DWORD,DWORD,DWORD) override { unimplemented("IDirect3DDevice7::DrawPrimitiveVB"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DrawIndexedPrimitiveVB(D3DPRIMITIVETYPE,LPDIRECT3DVERTEXBUFFER7,DWORD,DWORD,LPWORD,DWORD,DWORD) override { unimplemented("IDirect3DDevice7::DrawIndexedPrimitiveVB"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE ComputeSphereVisibility(LPD3DVECTOR,LPD3DVALUE,DWORD,DWORD,LPDWORD) override { unimplemented("IDirect3DDevice7::ComputeSphereVisibility"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetTexture(DWORD,LPDIRECTDRAWSURFACE7 *) override { unimplemented("IDirect3DDevice7::GetTexture"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetTexture(DWORD,LPDIRECTDRAWSURFACE7) override { unimplemented("IDirect3DDevice7::SetTexture"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetTextureStageState(DWORD,D3DTEXTURESTAGESTATETYPE,LPDWORD) override { unimplemented("IDirect3DDevice7::GetTextureStageState"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetTextureStageState(DWORD,D3DTEXTURESTAGESTATETYPE,DWORD) override { unimplemented("IDirect3DDevice7::SetTextureStageState"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE ValidateDevice(LPDWORD) override { unimplemented("IDirect3DDevice7::ValidateDevice"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE ApplyStateBlock(DWORD) override { unimplemented("IDirect3DDevice7::ApplyStateBlock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CaptureStateBlock(DWORD) override { unimplemented("IDirect3DDevice7::CaptureStateBlock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DeleteStateBlock(DWORD) override { unimplemented("IDirect3DDevice7::DeleteStateBlock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateStateBlock(D3DSTATEBLOCKTYPE,LPDWORD) override { unimplemented("IDirect3DDevice7::CreateStateBlock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Load(LPDIRECTDRAWSURFACE7,LPPOINT,LPDIRECTDRAWSURFACE7,LPRECT,DWORD) override { unimplemented("IDirect3DDevice7::Load"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE LightEnable(DWORD,BOOL) override { unimplemented("IDirect3DDevice7::LightEnable"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetLightEnable(DWORD,BOOL*) override { unimplemented("IDirect3DDevice7::GetLightEnable"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetClipPlane(DWORD,D3DVALUE*) override { unimplemented("IDirect3DDevice7::SetClipPlane"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetClipPlane(DWORD,D3DVALUE*) override { unimplemented("IDirect3DDevice7::GetClipPlane"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetInfo(DWORD,LPVOID,DWORD) override { unimplemented("IDirect3DDevice7::GetInfo"); return E_NOTIMPL; }
};
