"""Generate the export list of the renderer-trace proxy from the original _d3d.dll.

gen_d3dtrace.py <_d3d.dll> <out_dir>   ->  exports.h (X-macro list)
Only export names are taken from the game file; ordinals are kept so lookups by ordinal
would still match.
"""
import os, struct, sys

d = open(sys.argv[1], 'rb').read()
pe = struct.unpack_from('<I', d, 0x3c)[0]
nsec = struct.unpack_from('<H', d, pe + 6)[0]
optsz = struct.unpack_from('<H', d, pe + 20)[0]
opt = pe + 24
secs = [struct.unpack_from('<8sIIII', d, opt + optsz + i * 40) for i in range(nsec)]


def off(rva):
    for _, vsz, va, rsz, raw in secs:
        if va <= rva < va + max(vsz, rsz):
            return rva - va + raw
    raise ValueError(hex(rva))


e = off(struct.unpack_from('<I', d, opt + 96)[0])
base, nfun, nnames, afun, aname, aord = struct.unpack_from('<IIIIII', d, e + 16)
exports = []
for i in range(nnames):
    n = off(struct.unpack_from('<I', d, off(aname) + 4 * i)[0])
    exports.append((struct.unpack_from('<H', d, off(aord) + 2 * i)[0] + base, d[n:d.index(b'\0', n)].decode()))
exports.sort()

out = sys.argv[2]
# Some exports are C++-decorated (?name@@...), which a .def file cannot express (it cuts
# the name at '@'), so stubs are numbered and exported with /EXPORT:name=internal,@ordinal.
# The linker takes the internal name literally for a plain export (so it must be the COFF
# symbol "_stub_N") but adds the underscore itself for a decorated one ("stub_N").
# It still writes the 2 decorated names cut at the first '@'; harmless, the exe looks up
# only the 92 plain names (afDrawGroundTile2d / afSetDDGlobals are not referenced by it).
with open(os.path.join(out, 'exports.h'), 'w', newline='\n') as f:
    f.write('/* Generated by tools/gen_d3dtrace.py from the original _d3d.dll.\n'
            '   X(index, "export name", ordinal, "internal symbol for /EXPORT") */\n')
    for i, (ordinal, name) in enumerate(exports):
        internal = f'stub_{i}' if name.startswith('?') else f'_stub_{i}'
        f.write(f'X({i}, "{name}", {ordinal}, "{internal}")\n')
print(f'{len(exports)} exports')
