"""Generate logging stub base classes for DirectX 7 COM interfaces from the Windows SDK headers.

gen_com_stubs.py <sdk um include dir> <out header>

For every interface listed below, emits `struct <Iface>Stubs : <Iface>` whose methods all
log "unimplemented <Iface>::<Method>" and fail (E_NOTIMPL / 0). The real classes in
src/ddraw derive from these and override only what the game uses, so a call the game
makes that we have not implemented shows up in hogsdraw.log instead of crashing.
"""
import os, re, sys

INTERFACES = {
    'ddraw.h': ['IDirectDraw7', 'IDirectDrawSurface7', 'IDirectDrawPalette', 'IDirectDrawClipper'],
    'd3d.h': ['IDirect3D7', 'IDirect3DDevice7'],
}
METHOD = re.compile(r'STDMETHOD(?:_\((?P<rtype>[^,]+),\s*(?P<rname>\w+)\)|\((?P<name>\w+)\))\s*\((?P<args>[^;]*?)\)\s*PURE\s*;', re.S)


def methods(text, iface):
    m = re.search(r'DECLARE_INTERFACE_\(\s*' + iface + r'\s*,\s*IUnknown\s*\)\s*\{(.*?)\n\};', text, re.S)
    if not m:
        raise SystemExit(f'{iface} not found')
    for mm in METHOD.finditer(m.group(1)):
        rtype = (mm.group('rtype') or 'HRESULT').strip()
        name = mm.group('rname') or mm.group('name')
        args = ' '.join(mm.group('args').split())
        args = re.sub(r'^THIS_\s*', '', args)
        args = '' if args == 'THIS' else args
        yield rtype, name, args


out = ['/* Generated by tools/gen_com_stubs.py from the Windows SDK DirectX 7 headers. Do not edit. */',
       '#pragma once', '#include "common.h"', '']
for header, ifaces in INTERFACES.items():
    text = open(os.path.join(sys.argv[1], header), encoding='latin1').read()
    for iface in ifaces:
        out.append(f'struct {iface}Stubs : {iface} {{')
        for rtype, name, args in methods(text, iface):
            if name in ('QueryInterface', 'AddRef', 'Release'):
                continue  # every real class implements IUnknown itself
            ret = 'E_NOTIMPL' if rtype == 'HRESULT' else f'({rtype})0'
            out.append(f'    {rtype} STDMETHODCALLTYPE {name}({args}) override '
                       f'{{ unimplemented("{iface}::{name}"); return {ret}; }}')
        out.append('};')
        out.append('')
open(sys.argv[2], 'w', newline='\n').write('\n'.join(out))
print('ok', sys.argv[2])
